#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git rev-parse --abbrev-ref HEAD)

case $branch_name in
  "master")
    echo "        
        _ __ ___   __ _ ___| |_ ___ _ __ 
        | '_ ` _ \ / _` / __| __/ _ \ '__|
        | | | | | | (_| \__ \ ||  __/ |   
        |_| |_| |_|\__,_|___/\__\___|_|   
    "
    ;;
  *"feature"*)
    echo "
        Feature
    "
    ;;
  "hotfix")
    echo "
         _           _    __ _      
        | |__   ___ | |_ / _(_)_  __
        | '_ \ / _ \| __| |_| \ \/ /
        | | | | (_) | |_|  _| |>  < 
        |_| |_|\___/ \__|_| |_/_/\_\
    "
    ;;
  "develop")
    echo "
        Develop
    "
    ;;
  "release")
    echo "
                 _                     
        _ __ ___| | ___  __ _ ___  ___ 
        Release
    "
    ;;
  *)
    echo "You're on branch $branch_name. No ASCII art for this branch."
    ;;
esac
