#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg=$(cat $1)

branch_name=$(git rev-parse --abbrev-ref HEAD)

case $branch_name in
  "hotfix")
    if [[ $commit_msg == *"A corregir por:"* ]]; then
      echo "Todo correcto."
      exit 0
    else
      echo "Error: Utiliza el formato 'A corregir por: nombre de la persona.'"
      exit 1
    fi
    ;;
  *)
    echo "Todo correcto"
    ;;
esac